#pragma once


#define TAPPING_TERM 200

#define QUICK_TAP_TERM_PER_KEY

#define HOLD_ON_OTHER_KEY_PRESS
// #define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_TERM_PER_KEY


// combos
#define COMBO_PROCESS_KEY_RELEASE
#define COMBO_PROCESS_KEY_REPRESS
#define COMBO_TERM_PER_COMBO

#define CAPS_WORD_IDLE_TIMEOUT 0

#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RCTL
#define MODS_TO_NEUTRALIZE {MOD_BIT(KC_LALT), MOD_BIT(KC_RALT), MOD_BIT(KC_LGUI), MOD_BIT(KC_RGUI)}
